# Generated by Django 5.2.17 on 2026-10-04 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=9)),
                ('level', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='adviser_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdviserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('individual', 'Individual student'), ('level', 'Assigned level')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='accounts.adviserassignment')),
                ('recipients', models.ManyToManyField(related_name='adviser_messages', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='adviserassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'academic_session', 'level'), name='unique_adviser_staff_session_level'),
        ),
    ]
