# Generated by Django 5.2.17 on 2026-10-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adviserassignment_advisermessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisermessage',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('send_adviser_message', 'Can send adviser messages')]},
        ),
    ]
