# Generated by Django 5.2.17 on 2026-10-05 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_advisermessage_options'),
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('adviser', 'Assigned adviser'), ('individual', 'Individual student'), ('level', 'Student level')], max_length=20)),
                ('academic_session', models.CharField(max_length=9)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adviser_recipients', models.ManyToManyField(blank=True, related_name='received_hod_messages', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(blank=True, related_name='hod_messages', to='students.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_hod_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
