"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import secrets
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or secrets.token_urlsafe(50)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# The React client is served from its own origin, so its development address must be
# trusted for csrf. Values come from DJANGO_CSRF_TRUSTED_ORIGINS and stay empty until
# a frontend origin is agreed; do not add "*" here.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Production transport hardening for deployments served over HTTPS. Development
# and the test suite run over plain HTTP, so the transport flags are opt-in
# through DJANGO_SECURE_TRANSPORT and must be enabled where TLS terminates.
# SECURE_HSTS_SECONDS defaults to one year when transport hardening is on;
# dial it down deliberately before enabling include_subdomains or preload, and
# never enable them without confirming every subdomain serves HTTPS.
_SECURE_TRANSPORT = os.environ.get("DJANGO_SECURE_TRANSPORT", "").lower() in {
    "1",
    "true",
}
SESSION_COOKIE_SECURE = _SECURE_TRANSPORT
CSRF_COOKIE_SECURE = _SECURE_TRANSPORT
SECURE_SSL_REDIRECT = _SECURE_TRANSPORT
SECURE_HSTS_SECONDS = int(
    os.environ.get("DJANGO_SECURE_HSTS_SECONDS")
    or ("31536000" if _SECURE_TRANSPORT else "0"),
)

# Response hardening that is safe in every environment, including development.
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# Staff sessions must not live for Django's default two weeks: a session that
# holds access to student records expires after twelve hours unless the
# environment overrides it with DJANGO_SESSION_COOKIE_AGE_SECONDS.
SESSION_COOKIE_AGE = int(
    os.environ.get("DJANGO_SESSION_COOKIE_AGE_SECONDS") or str(12 * 60 * 60),
)

# Failed sign in attempts are counted in this cache. LocMem keeps the counters
# inside this process, which is correct while the API runs as one process in
# development, tests and a small single-server deployment. When several
# processes or servers must share the counters, replace this block with a Redis
# cache backend; the login code does not change because every read and write
# already goes through django.core.cache.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "oau-eee-student-api",
    }
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "students.apps.StudentsConfig",
    "accounts.apps.AccountsConfig",
    "academics.apps.AcademicsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Production requires a stable secret and deployment-specific settings.
if not DEBUG and not os.environ.get("DJANGO_SECRET_KEY"):
    raise RuntimeError("Set DJANGO_SECRET_KEY when DEBUG is disabled.")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAdminUser",
    ],
}

CURRENT_ACADEMIC_SESSION = os.environ.get(
    "CURRENT_ACADEMIC_SESSION",
    "",
)


# React uses a same-origin /api proxy; no permissive CORS middleware is enabled.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = SESSION_COOKIE_SECURE or not DEBUG
CSRF_COOKIE_SECURE = CSRF_COOKIE_SECURE or not DEBUG
PASSWORD_RESET_FRONTEND_URL = os.environ.get("PASSWORD_RESET_FRONTEND_URL", "")
PASSWORD_RESET_TIMEOUT = 3600
EMAIL_BACKEND = os.environ.get("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_USE_TLS", "true").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_DEFAULT_FROM_EMAIL", "noreply@example.invalid")
REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
    "password_reset": "20/hour", "password_reset_confirm": "60/hour",
}


# Bulk guardian reports stay disabled until providers are configured.
RESULT_SHARING_ENABLED = os.environ.get("RESULT_SHARING_ENABLED", "false").lower() == "true"
EMAIL_TIMEOUT = 20
WHATSAPP_ACCESS_TOKEN = os.environ.get("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_API_VERSION = os.environ.get("WHATSAPP_API_VERSION", "")
WHATSAPP_RESULT_TEMPLATE = os.environ.get("WHATSAPP_RESULT_TEMPLATE", "")
WHATSAPP_TEMPLATE_LANGUAGE = os.environ.get("WHATSAPP_TEMPLATE_LANGUAGE", "")
