# Generated by Django 5.2.17 on 2026-10-04 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier_type', models.CharField(choices=[('matriculation', 'Matriculation number'), ('utme', 'UTME number')], max_length=20)),
                ('identifier_value', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=30)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('mode_of_admission', models.CharField(choices=[('utme', 'UTME'), ('direct_entry', 'Direct Entry'), ('transfer', 'Transfer')], max_length=20)),
                ('current_level', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['full_name', 'student_id'],
            },
        ),
    ]
