# Generated by Django 5.2.17 on 2026-10-06 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduated', 'Graduated')], default='undergraduate', max_length=20),
        ),
    ]
