# Generated by Django 5.2.17 on 2026-10-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_academic_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name', 'student_id'], 'permissions': [('export_student', 'Can export student profiles')]},
        ),
    ]
