# Generated by Django 5.2.17 on 2026-10-07 05:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_academic_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('harmattan', 'Harmattan'), ('rain', 'Rain')], max_length=10)),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('credit_units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.academicsession')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('credit_units', models.PositiveSmallIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_verified', models.BooleanField(default=False)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='academics.courseoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'academic_session', 'semester'), name='unique_course_session_semester'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('student', 'offering', 'attempt_number'), name='unique_student_offering_attempt'),
        ),
    ]
