# Generated by Django 5.2.17 on 2026-10-07 17:37

from django.db import migrations, models


def seed_initial_scale(apps, schema_editor):
    Scale = apps.get_model("academics", "GradingScale")
    Scale.objects.using(schema_editor.connection.alias).create(
        name="Initial five-point scale",
        is_published=True,
        bands=[
            {"minimum": "0", "maximum": "40", "grade_point": "0"},
            {"minimum": "40", "maximum": "45", "grade_point": "1"},
            {"minimum": "45", "maximum": "50", "grade_point": "2"},
            {"minimum": "50", "maximum": "60", "grade_point": "3"},
            {"minimum": "60", "maximum": "70", "grade_point": "4"},
            {"minimum": "70", "maximum": "100", "grade_point": "5"},
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bands', models.JSONField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.RunPython(seed_initial_scale, migrations.RunPython.noop),
    ]
