# Generated by Django 5.2.17 on 2026-10-07 18:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_result_options_courseoffering_grading_scale_and_more'),
        ('students', '0005_alter_student_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField()),
                ('history_digest', models.CharField(max_length=64)),
                ('cgpa_snapshot', models.CharField(max_length=100)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='graduation_review', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('result', 'Recorded result required'), ('exemption', 'Reviewed exemption'), ('transfer', 'Reviewed transfer credit')], default='result', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.courseoffering')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_requirements', to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'offering'), name='unique_student_course_requirement')],
            },
        ),
    ]
