# Generated by Django 5.2.17 on 2026-10-08 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_graduationreview_courserequirement'),
        ('students', '0006_merge_academic_status_surname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianSharingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('evidence', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result_sharing_preference', to='students.guardian')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultShareBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('harmattan', 'Harmattan'), ('rain', 'Rain')], max_length=10)),
                ('student_ids', models.JSONField()),
                ('channels', models.JSONField()),
                ('preview', models.JSONField()),
                ('history_digest', models.CharField(max_length=64)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicsession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultShareDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('destination', models.CharField(blank=True, max_length=254)),
                ('part_number', models.PositiveSmallIntegerField(default=1)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Ready for review'), ('queued', 'Queued'), ('processing', 'Submission in progress'), ('accepted', 'Accepted by provider'), ('failed', 'Rejected or not submitted'), ('unknown', 'Submission outcome uncertain'), ('skipped', 'Skipped'), ('cancelled', 'Contact or permission changed')], db_index=True, default='draft', max_length=20)),
                ('diagnostic_code', models.CharField(blank=True, max_length=50)),
                ('provider_id', models.CharField(blank=True, max_length=200)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='academics.resultsharebatch')),
                ('guardian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'guardian', 'channel', 'part_number'), name='unique_guardian_channel_part_per_share_batch')],
            },
        ),
    ]
